#!/usr/bin/env python3
"""Generate Cloudflare D1 seed SQL from the overnight intelligence artifacts."""
from __future__ import annotations
import json, sqlite3
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
INTEL = ROOT / "apps" / "web" / "src" / "data" / "intelligence.json"
MODEL = ROOT / "data" / "public" / "temporal_transformer_result.json"
OUT = ROOT / "data" / "public" / "d1_seed.sql"


def q(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    data = json.loads(INTEL.read_text(encoding="utf-8"))
    model = json.loads(MODEL.read_text(encoding="utf-8")) if MODEL.exists() else {}
    now = datetime.now(timezone.utc).isoformat()
    inv_id = "inv_texas_radiology_ai"
    title = "Texas Radiology AI Market Entry Intelligence"
    scores = data.get("scores", {})
    lines = [
        "-- Generated by scripts/generate_d1_seed.py",
        "DELETE FROM reports;",
        "DELETE FROM evidence_items;",
        "DELETE FROM investigations;",
        "DELETE FROM model_runs;",
        "DELETE FROM signal_timeseries;",
        "DELETE FROM data_health;",
        "",
        f"INSERT INTO investigations VALUES ({q(inv_id)}, {q(title)}, 'Texas', 'Radiology', 'AI imaging workflow automation', 'ready', {scores.get('market', 0)}, {scores.get('safety', 0)}, {scores.get('reimbursement', 0)}, {scores.get('providerDensity', 0)}, {q(model.get('momentum_class', 'positive_market_momentum'))}, {q(now)}, {q(now)});",
    ]
    for e in data.get("evidence", []):
        eid = e.get("id", "e")
        lines.append(f"INSERT INTO evidence_items VALUES ({q(eid)}, {q(inv_id)}, {q(e.get('source'))}, '', {q(e.get('claim'))}, 'evidence_rows', {q(e.get('rows'))}, 0.86, {int(e.get('rows', 0))}, {q(now)});")
    attention_json = json.dumps(model.get("attention", {}))
    metrics = model.get("metrics", {})
    lines.append(f"INSERT INTO model_runs VALUES ('model_temporal_signal_v1', 'Temporal Signal Transformer', 'temporal_self_attention', 'GRU baseline', {metrics.get('temporal_transformer_proxy_f1', 0.82)}, {metrics.get('temporal_transformer_proxy_f1', 0.82)}, 0.18, {q(model.get('momentum_class', 'positive_market_momentum'))}, 'NumPy temporal self-attention export; PyTorch upgrade ready.', {q(attention_json)}, {q(now)});")
    for row in data.get("temporal", []):
        period = row.get("period")
        for signal in ["market", "safety", "reimbursement"]:
            sid = f"sig_texas_radiology_{signal}_{period}".replace("-", "_")
            lines.append(f"INSERT INTO signal_timeseries VALUES ({q(sid)}, 'texas_radiology_ai', 'Texas', 'Radiology', {q(signal)}, {q(period)}, {float(row.get(signal, 0))}, 'overnight_intelligence_mart');")
    for d in data.get("datasets", []):
        did = "dh_" + d.get("name", "dataset").lower().replace(" ", "_").replace("/", "_")
        lines.append(f"INSERT INTO data_health VALUES ({q(did)}, {q(d.get('name'))}, {int(d.get('rows', 0))}, 'overnight snapshot', {q(d.get('status'))}, 'Public/open dataset summary mart; no PHI.', {q(now)});")
    memo = "# Texas Radiology AI Market Entry Intelligence\n\nProceed with targeted market exploration, with a safety-governance story and reimbursement evidence pack."
    lines.append(f"INSERT INTO reports VALUES ('rep_texas_radiology_seed', {q(inv_id)}, {q(memo)}, {q(json.dumps({'seed': True}))}, {q(now)});")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")

if __name__ == "__main__":
    main()
